### ISSUE TITLE
Venus blessing, monument building, and supply posts

### ISSUE THREAD

**Issue by Lastarael** [Keriew/augustus#638] opened 2022-07-24 23:37 UTC
Hi!  First of all, thanks so much for creating and supporting Augustus!  I've been really enjoying the game, and overall feel like the changes made in the mod really improve the experience.  I really, really wish I'd found this forum a while ago, because I've been Googling some Augustus gameplay changes not finely detailed in the user manual, and have watched hours and hours of GamerZach's videos trying to find the answers to no avail.

My first question is regarding the Venus blessing.  The boost to the labor pool that comes with her blessing makes managing a large city very difficult.  The last few missions I've specifically tried to avoid getting her blessing without outright pissing her off, because it just really throws my employment situation for a loop.  I always strive to keep my people happy and typically keep sentiment around "loved" or "idolized" and have no trouble whatsoever with crime, except after receiving a blessing from Venus.  I'll go from having no employment problems and idolized sentiment to having 700+ unemployment and instant crime with back-to-back notifications.  Then I have to go around finding temporary jobs for hundreds of people, only to have to mothball the buildings once the blessing ends.  Is there any way to disable this feature, or prevent Venus's blessing once a Pantheon is built?  I was trying to do it by skipping her festivals, since I'm leery about shorting her a temple, but the annual festival held by the Pantheon rendered that approach moot.  Surely this isn't how a blessing from a god is supposed to work, right?

My second question is regarding monuments.  I saw in one of GamerZach's videos that you only need one Architect's guild, but even when I build a bunch of work camps and have 'getting' warehouses as close as possible, it takes years to finish building one monument.  I've started just trying to build palaces without a coliseum or hippodrome, because the one time I tried to build the latter I wound up having to put off my promotion many times to finally see it completed, and it's just not worth building the monuments if you no longer need them by the time they're finally finished.  Is there some way that I'm missing to speed this process up, preferably without having to shoehorn in a ton of warehouses and work camps right next to the building site when space is limited, such as in my palace blocks?

And my final questions are regarding supply posts.  Do they need to be built near barracks or forts?  And is there any way to prevent them from stocking many years' worth of food when I'm struggling to feed my citizens?  I've tried devoting a single granary to the supply post and limiting the food that it stocks to 8 of each, but somehow my supply post still collects thousands of units of food.

Lastly, I encountered a bug in Caesarea (peaceful Consul mission) - a stuck looter leftover from the beginning of the mission that threw off my crime rating for years, and disappearing prefects.  I managed to complete the level without too many problems, and they eventually resolved on their own somehow, so I wasn't sure if y'all would still want a bug report.  I can create a new thread and link the save if so, just let me know.

Sorry for writing a book here.  Thanks for making it to the end, and for any help you can provide.

**Comment by Keriew** [comment] 2022-08-01 18:26
Hey, thanks for the reports!

About the Venus blessing - it causing problems is the issue that we haven't considered and is something I'll look into.

As of the monuments - all the building process is done by the walkers using the road network, and to efficiently build monuments you have to take that into consideration. A foreman from the work camp has to go to the warehouse and grab the resources, then head to the monument site. If the work camps are far from the warehouses,or the warehouses with necessary resources are far from the monument sites the delivery process can take a long time. To speed it up, you can make sure that warehouses with construction materials are close, or you can build multiple work camps to haul more materials at the same time. Work camps don't necessarily have to be close to the monument, it's equally as efficient if they are close to the resource warehouses. A monument only needs a couple of visits from the Architect's guild, so they are usually not a bottleneck, even in if they are far away and you are building multiple monuments.

Supply post doesn't have to be near the barracks or forts, they don't interact with each other. As to supply post collecting a lot of food, I can agree that the granary sort of control of how much it stockpiles could be useful. That'd be a nice addition.

If you still have the same with the bugged looters/prefects, I'd like that save if you still have it. It would make it much easier to figure out what's wrong and how to fix it.

**Comment by Lastarael** [comment] 2022-08-13 06:01
Thanks for your replies!  Sorry it took so long for me to get back to you - Real Life struck and I had to divide my attentions for a while.

With your advice I've tried out different layouts as far as work camps, warehouses with necessary materials, and monument locations go, and now I'm still surprised every time at how fast they shoot up compared to my previous experiences.  Perhaps mentioning how that dynamic works in the next user manual would be helpful to others as well.

I look forward to what tweaks you may implement in the next version as far as the Venus blessing and extra control of how much food the supply post collects.  Currently I don't have too many problems with it once I build a granary only accepting a limited amount of the two foods not eaten by the rest of my citizens, accessible only to the supply post, and another granary only accepting 8 of the main food supply, also only accessible to the supply post.  The rest of the granaries I make sure to not allow the supply post access, and it works fairly well that way, but then again I haven't been playing on any more maps with limited food supplies lately.

One other suggestion I'd like to put forward for the next patch, if it's possible to program, is a hotkey shortcut to easily disable/mothball a building or re-enable it.  Since I've been playing the game again I've been experiencing a new pain in my right thumb and wrist from all the right-clicking I do, and enabling/disabling buildings, especially during times of extreme changes in population or variations of the available workforce, is a very large part of that.  I very rarely want to mothball an entire industry, so going through each building one at a time requires a lot of repetitive clicking.

And, I'm attaching the file with the prefect and looter bugs.  If you look at the neighborhood on Crime overview it should be readily apparent.
It's located in the old city on the Caesarea level, which I redeveloped into an export center.   When the prefectures started disappearing I just added a bunch more as a temporary measure to stave off all the fire outbreaks.
![city 2022-08-13 01 16 45](https://user-images.githubusercontent.com/109925070/184470314-d8df9a4b-6f73-4592-9678-da6cca34a91c.png)
The looter is stuck in this house below the tooltip to the right.
![city 2022-08-13 01 16 57](https://user-images.githubusercontent.com/109925070/184470345-e7436793-4857-47a2-bdeb-d7fdaa198600.png)
![city 2022-08-13 01 17 09](https://user-images.githubusercontent.com/109925070/184470436-0305911d-8a61-4f24-982f-46976304f1e4.png)
I've tried tearing down those houses, sending my soldiers onto that street to see if they would kill the looter, and nothing I did got rid of him.  For years after, my Crime Advisor would say "Some areas have high crime levels" when this looter was the only thing on the crime map.  Eventually, just like the disappearing prefects, he vanished, and the problem resolved itself somewhere between 15 and 20 AD, but I have no idea how or why.

Unfortunately, it is not letting me share the .svx file of that game.  Is there another way to post save files for other people to open in their game so that you can see the bug in real time?

**Comment by crudelios** [comment] 2022-08-13 06:35
This is somewhat unrelated, but if you're getting a pain in the wrist make sure you have a mouse big enough for your hand and that you're correctly positioned.

I have fairly large hands and when I used those smaller, laptop-styled mouse I stated getting a strong constant pain in my wrist that lasts a few days. Changing to a regular mouse and improving my posture gets rid of the pain.

Even now if I need to use a smaller mouse or don't sit properly I get the pain again.

Just something to consider!

**Comment by Keriew** [comment] 2022-08-13 08:55
> Unfortunately, it is not letting me share the .svx file of that game. It says it's not an accepted file format. Is there another way to post save files for other people to open in their game so that you can see the bug in real time?

You have to zip the file first.

**Comment by Lastarael** [comment] 2022-08-13 19:34
> You have to zip the file first.

Oh, yeah, that makes sense.  Doh!
[Lastarael - Caesarea Bug.zip](https://github.com/Keriew/augustus/files/9332027/Lastarael.-.Caesarea.Bug.zip)



> This is somewhat unrelated, but if you're getting a pain in the wrist make sure you have a mouse big enough for your hand and that you're correctly positioned.

I actually play from a recliner and don't have a desk, so I use a keyboard with a built-in mouse stick (Lenovo compact keyboard with trackpoint) that sits in my lap.  I've used this setup without any pain for over a decade, but I've also never right-clicked so much in my life.  I've got various wireless mice I've tried in the past, including some with roller balls that don't require a hard surface to use, but no ideal place to put them.  Though now that you've brought that up, I might try placing one of them on the end table nearby and when I'm going to have to do a lot of right-clicking I'll see if using that prevents some strain, or if the awkward angle makes it too uncomfortable.  Thanks for the suggestion!

**Comment by Hraesvelg** [comment] 2022-11-05 12:29
Hi all,

thanks too for this mod ! and i join the first question of @Lastarael in his first post...

the blessing of Venus to rejuvenate people is a big problem 
each time when you try to stabilize your city, Venus trigger the blessing (even if you disable temple...), and directly we have got ~ 2 peaks in an age's category. 

ok you can create a fake industry in first time but after when people become too old.. delete the fake industry is not enough because in the same time, the births are very too low... 

so i don't know what is the best compromise...

**Comment by QmwJlHuSg9pa** [comment] 2023-01-08 18:18
> but somehow my supply post still collects thousands of units of food.

Oof, this is why I've now failed half-a-dozen attempts at mission 4 (Syracusae):

"Months of food stored: **774**".

No wonder I was unable to sustain revenue with trading, whilst dealing with constant riots due to food shortages.

I don't understand what the Roman army is going to do with 65 years worth of vegetables and wheat? This maybe needs a sane cap, or default to a less aggressive "gather" priority.

**Comment by crudelios** [comment] 2023-07-25 16:28
@Keriew I think the crazy supply post storage has been fixed, right?

Regarding the looter bug: it was most likely caused by the vacant lot houses being occupied by an immigrant while the looter was there. The looter then got stuck.

Curiously enough, the looter seems to be eternally fighing a cavalary unit.

**Comment by Keriew** [comment] 2023-07-25 17:15
Right, the supply post storage was fixed.

**Comment by crudelios** [comment] 2023-08-02 20:25
I'm hoping the cause of the stuck rioter was a bogus bug as I don't know what caused it.

On the savefile, deleting the house and adding roads around the rioter allows the prefects to kill it.

I'm closing this as fixed.

**Closed by crudelios** 2023-08-02 20:25 UTC
Labels: question
