### ISSUE TITLE
Dock placement in Londinium not possible

### ISSUE THREAD

**Issue by Caribou115** [Keriew/augustus#1020] opened 2024-01-18 21:00 UTC
Hello,

In the Londinium map I am not able to place a dock anywhere on the map. I keep getting the error that 'this inland lake has no access to the sea'. 

EDIT: Same in Lindum.  I'm using augustus 4.0

**Comment by Ouaz** [comment] 2024-01-25 22:20
Could you provide a save ?

I tested both in 4.0 and latest unstable, and I can place docks and wharves both on Londinium (campaign and CCK) and Lindum.

**Comment by Caribou115** [comment] 2024-01-26 10:17
[Reconquered - 17 Londinium.zip](https://github.com/Keriew/augustus/files/14063399/Reconquered.-.17.Londinium.zip)
[Reconquered - 19 Lindum.zip](https://github.com/Keriew/augustus/files/14063403/Reconquered.-.19.Lindum.zip)

I tried again and now somehow the issue is gone in Londinium, but in Lindum still not possible to place docks.

**Comment by crudelios** [comment] 2024-01-26 10:34
Ah this is the Reconquered campaign, not the original one.

This is most likely an issue with the scenario itself, not with augustus. I'll refer the issue to the campaign's creator so he can look into it and close this as not a bug.

**Closed by crudelios** 2024-01-26 10:34 UTC
Labels: bug
