### ISSUE TITLE
Movement hotkeys clash with other hotkeys

### ISSUE THREAD

**Issue by brainwad** [Keriew/augustus#408] opened 2021-05-25 12:27 UTC
I have movement keys bound to WASD as well as arrow keys. I moved the default hotkeys for water, problems and damage overlays to Shift+W, +S and +D respectively, and also mapped clinic to Shift+A.

When I press these shift hotketys, they do work, but the screen also moves as if I had pressed the key without shift (so Shift+W toggles water overlay _and_ moves screen up, Shift+A selects doctor's clinic and moves screen left).

This problem appears only for movement keys; I have other combinations that do not do this (e.g. Q for rotate anticlockwise and Shift+Q for prefecture; 1 for employment advisor and Shift+1 for housing plot; R for rotate building clockwise and Shift+R for rotate building anticlockwise).

The correct behaviour should be for hotkeys with more modifier keys active to take precedence over ones with fewer modifier keys.

**Comment by crudelios** [comment] 2021-05-25 12:58
@bvschaik This is a Julius issue.

**Comment by bvschaik** [comment] 2021-05-25 15:08
Interesting one, it was caused by the arrow keys (or whichever keys are mapped to them) being handled differently from the other hotkeys. I fixed it in Julius.

**Comment by crudelios** [comment] 2021-05-27 18:39
Since this is fixed in Julius, I'll be closing this and eventually when the latest Julius changes get merged this will also be fixed here.

**Closed by crudelios** 2021-05-27 18:39 UTC
Labels: bug
