### ISSUE TITLE
Market Displays Wrong Color Letters 

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#73] opened 2020-06-09 17:23 UTC
I'm currently running Augustus 1.41 and i notice a random reddish letter color (goods) on the information panel of markets, as imagens below show.

![Market](https://user-images.githubusercontent.com/64329357/84179623-274a3f80-aa7e-11ea-93da-63c67d0f5d26.jpg)

![Market 2](https://user-images.githubusercontent.com/64329357/84179637-2ca78a00-aa7e-11ea-934b-f0f66b3aedea.jpg)

**Comment by Keriew** [comment] 2020-06-09 17:34
By design it shows black letter for the goods that the market accepts and red letters for the goods the market doesn't accept. Is this behaving improperly?

**Comment by arkimedes1967** [comment] 2020-06-09 19:19
Not at all. It helps us to see a quick information of the market. Thank you!

I confess i didn't realise that. Is this new on Augustus or by default on C3?

**Comment by Keriew** [comment] 2020-06-09 19:30
Base Caesar 3 doesn't have market special orders, so that's Augustus addition. It's not the first time it's been reported as a bug, so I guess it's not very intuitive. 

With that resolved, closing the issue.

**Closed by Keriew** 2020-06-09 19:30 UTC
Labels: bug
