### ISSUE TITLE
Fountains shown green before placing over anything

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/augustus#166] opened 2020-12-09 15:45 UTC
You can attempt to place fountains over whatever obstacles: buildings terrains etc
Of course, it won't work, when you click it shows "must be built on clear land" message.
Felt strange since for other objects, aqueducts, e.g, it shows them with red if you hover over an obstacle.

![Capture](https://user-images.githubusercontent.com/13402104/101651910-43876300-3a46-11eb-831b-2420b4ae595e.JPG)

**Comment by crudelios** [comment] 2020-12-11 09:45
@bvschaik and I are discussing whether this should be fixed on base Julius.

The question is: is this a bug or did the developers actually intend it to work this way, so the player could always see the water range?

**Comment by onurarpapay** [comment] 2020-12-14 10:46
I think this is not a bug but a feature, I like to see the range of a fountain for planning purposes -- perhaps I can think of deleting that temple and putting the fountain instead. Fountain ghost image might be "red" in this case perhaps, but I would always show the range.

**Comment by theradeonxt** [comment] 2020-12-14 12:29
Well, there are valid points here to keep the behavior unchanged.
I understand sometimes you may want to know in advance what the area covered by fountain will be, before removing a building, for example.

The only inconsistency then remains in case of Reservoirs - should it work the same as fountains before placing it?

If there's no other things here I guess this can be closed.

**Comment by crudelios** [comment] 2020-12-14 13:01
Just to add fuel to the flames, bathhouses also need water supply information but appear as red when they are blocked by buildings/terrain.

**Comment by crudelios** [comment] 2020-12-21 17:08
After consideration I think we can say this may be a feature rather than a bug. If there's no serious opposition against keeping this behaviour, I'll close this issue in a few days.

**Comment by webfischi** [comment] 2020-12-23 11:53
Is it impossible to change the color of the fountain to red when the "ghost" fountain is red? How hard coded is it? When it is just a texture laying on top of the "ghost" fountain, why not put the "ghost" fountain on top or remove the fountain from that texture so it shows the "ghost" fountain?

**Comment by crudelios** [comment] 2020-12-23 12:35
That is doable and would work!

@bvschaik what do you think, even for Julius?

Here's how it would look:

![city 2020-12-23 12 34 29](https://user-images.githubusercontent.com/6518876/102996590-46d91f00-451b-11eb-8d14-209493215fd6.png)

**Comment by crudelios** [comment] 2021-01-16 08:49
Fixed in Julius, will eventually find its way to Augustus!

**Closed by crudelios** 2021-01-16 08:49 UTC
Labels: bug
