### ISSUE TITLE
Londinium Issues

### ISSUE THREAD

**Issue by Bestiuk** [Keriew/augustus#484] opened 2021-09-13 04:50 UTC
The Caravanserei is broken on this map. The workers will deliver the necessary timber and marble, but they will not delivery any clay, no matter what I do. 

Also, the trade ships do not enter the map often enough. I am unable to import enough Oil to achieve the housing level for the prosperity target. The max I am able to import is 7 per year with my docks located in the closest available position to the entrance of the map.

**Comment by crudelios** [comment] 2021-09-13 11:03
Hi, are you using v3.0 or the latest unstable?

**Comment by Bestiuk** [comment] 2021-09-13 13:39
Hi Jose,

I am using 3.0.1

I've also noticed a bug with the Arenas. The gladiators will walk from the
school to the arena, but they will always disappear into the arena and
never walk beyond it.

**Comment by crudelios** [comment] 2021-09-13 13:41
3.0.1 has some bugs, including a problem with too few traders appearing and with the colosseum as well.

We are planning to launch v3.1 soon(ish) which will fix those issues.

Regarding clay not being delivered: do you by any chance have a monument with halted construction?

**Comment by Bestiuk** [comment] 2021-09-13 13:44
Ok sounds good!

No, it is not halted. The workers delivered all of the other needed
materials, but they won't touch the clay.

**Comment by crudelios** [comment] 2021-09-13 13:48
Can you provide the city save, please? That way I can test whether the clay issue is already fixed on the current unstable version.

**Comment by Bestiuk** [comment] 2021-09-13 13:54
Sure, no problem. Here it is!

**Comment by crudelios** [comment] 2021-09-13 13:58
I don't think you can send it as an e-mail attachment, rather you have to upload it from github itself :\

**Comment by Bestiuk** [comment] 2021-09-13 14:17
I tried that yesterday when I submitted the issue and it told me it was an
unrecognizable file format. Is there another way?

**Comment by crudelios** [comment] 2021-09-13 14:26
Try zipping the file first and it should work! 👍

**Comment by crudelios** [comment] 2021-10-05 18:51
Since there have been no developments with this bug, I'm closing it as fixed.

**Closed by crudelios** 2021-10-05 18:51 UTC
Labels: bug

**Comment by crudelios** [comment] 2021-10-05 22:43
No problem, if you can, please place the savefile here anyway so I can confirm there are no problems!

**Comment by Bestiuk** [comment] 2021-10-05 23:48
Ok, I am away from my computer for another week but I'll upload it as soon
as I can.
