### ISSUE TITLE
Ballistae failing to fire?

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#49] opened 2020-06-03 12:33 UTC
Why do the ballistae sometimes fail to fire? I can't seem to find any pattern as to the cause of this problem, either. It's not an issue of rate of fire because there will be enemies in range, and one ballista will fire while the one next to it will not.

I tend to build walls bristling with ballistae, as you can see below. I think that if the ballistae would fire consistently, then my walls should be doing most of the work. (For anyone wondering, plazas make a terrific grid system that makes it easier to precisely place your troops. Plus, they just look good and they're sort of a deceptive "welcome mat" for your enemies. At least they get to die in a pretty place.)

![Lutetia_towers](https://user-images.githubusercontent.com/9805709/83636904-576c7c80-a56c-11ea-9a41-a64e555d2077.png)

**Comment by crudelios** [comment] 2021-01-22 09:48
Has anyone managed to reproduce this? For me ballistas have always worked...

**Comment by Keriew** [comment] 2021-01-23 15:23
I think the _issue_ may be that ballistas can only fire over towers/walls/trees in a limited range, so depending on the position of the tower and the angle of the shot, not all towers may be able to shoot (all the towers in the picture are behind at least double layer of wall, which makes me think it's the case). This seems to be a balancing mechanic intended to stop multiple layers of towers and it's not explained anywhere in game. But it does seem to be working as designed. I'm going to close the issue. If anyone else encounters this, please open a new one.

**Closed by Keriew** 2021-01-23 15:23 UTC
Labels: question
