### ISSUE TITLE
Augustus 3.2.0 - Random crashes while playing with italian language files

### ISSUE THREAD

**Issue by FabianoVeglianti** [Keriew/augustus#877] opened 2023-05-27 15:36 UTC
I tried to reproduce the crash deterministically, but it appears to be random. In game the first time the game crashed I was removing trees; the second time it crashed after I build the barraks.

Both times in _augustus-log.txt_ there was the same things, I will attach the file.
[augustus-log.txt](https://github.com/Keriew/augustus/files/11582365/augustus-log.txt)

Other than Augustus 3.2.0 files, I changed the _wavs_ and _smk_ folders to have audio in italian and I changed the following files to have language (interface) in italian _C3.ENG_, _c3_mm.eng_ _C32.EMP_ and _c3.emp_. All those files can be downloaded [here ](https://pastebin.com/mj3gtHrp).

I tried to delete those files (using the steam's repairing tool) and I played for some time without getting any crash.
I don't expect you to take care of this immediately, but I'm posting it to make you aware of it. Plus, if you give me some hint about how to solve this I can try to do it by myself in my free time, I'm a computer engineer guy.

EDIT: it happens again (without the files for italian language), this is the new log.
[augustus-log.txt](https://github.com/Keriew/augustus/files/11582434/augustus-log.txt)
This time, in game, I builded the wine factory just before the crash.

**Comment by crudelios** [comment] 2023-05-27 16:25
There is a known crash on v3.2.0 related to rioters appearing, so it feels seemingly random. If that's the cause it should be fixed on the latest unstable.

**Comment by FabianoVeglianti** [comment] 2023-05-27 18:40
No, I don't think that's the case because I tried more than once and at different times crashes (neither of these times did a riot break out).

**Comment by crudelios** [comment] 2023-05-27 20:57
It could still crash even if there is no riot.

Please do test on the unstable version first, just be sure to not overwrite your saves as they are not compatible with v3.2.0.

The reason I ask this is because v3.2.0 is almost a year old, so you issue is probably fixed already anyway.

**Comment by crudelios** [comment] 2023-06-27 13:16
I'm closing this due to inactivity. It's also likely it has been fixed on unstable anyway.

**Closed by crudelios** 2023-06-27 13:16 UTC
Labels: bug
