### ISSUE TITLE
Augustus crashing 

### ISSUE THREAD

**Issue by SlaxPT** [Keriew/augustus#917] opened 2023-07-16 13:58 UTC
![Captura de ecrã 2023-07-16 144938](https://github.com/Keriew/augustus/assets/139695388/0ddcbb95-eee6-4be1-a69f-f856e4371890)
Sometimes when i try to either save the game or just normally getting back to the menu, it crashes and this phrase appears,

**Comment by SlaxPT** [comment] 2023-07-16 13:59
PS: I´m using the last release, 3.2 windows 11 home

**Comment by crudelios** [comment] 2023-07-16 14:15
The 3.2.0 is now quite old, even though it's the latest release. Does the issue still happen on the latest unstable?

Also, when saving, when exactly does the crash happen? When you click the "save game" window or when actually saving?

**Comment by SlaxPT** [comment] 2023-07-16 17:05
> The 3.2.0 is now quite old, even though it's the latest release. Does the issue still happen on the latest unstable?
> 
> Also, when saving, when exactly does the crash happen? When you click the "save game" menu button or when actually saving?

Didn't try unstable version yet but yes, it happens whenever i try to save the game (I enter a simple name, then press save and it crashes), exit caesar from the menu, sometimes when starting a new mission, like mission 5.

**Comment by crudelios** [comment] 2023-07-25 16:07
The most recent versions of the latest unstable have a better log of the error on crash, so if you can try it there I'd be glad.

Otherwise I'll eventually close this due to inactivity since it's likely a duplicate of #881 and #914 and should be fixed on the latest unstable.

**Comment by SlaxPT** [comment] 2023-07-25 19:15
I was a bit busy lately, sorry for that. 

I'm currently using the unstable version augustus-3.2.0.528-16b353a6 and it's not crashing anymore, but it has some visual bugs, like road block appearing on top of the granary. I'm gonna test the latest unstable to see if it fixes it. Thank you.

**Comment by crudelios** [comment] 2023-07-25 19:16
Ah, for the visual bus get the latest development assets, you cash get them from the main page next to the windows build.

Actually delete the old assets folder and copy the new one, don't just copy one over the other. That should sort out your issues.

**Comment by crudelios** [comment] 2023-07-25 22:25
Marking as fixed on unstable.

**Closed** 2023-07-25 23:08 UTC
Labels: bug
