### ISSUE TITLE
Hotkey for important build options including "Clear Land"

### ISSUE THREAD

**Issue by daish0** [Keriew/augustus#80] opened 2020-06-13 17:09 UTC
Once could possibly want a hotkey for each building, but that can get out of hand quickly.
Some build options are used quiet often though, maybe build houses. But it would be really nice if we have a shortcut option for "Clear Land" (latest Anno did this I think which is quiet handy).

**Comment by crudelios** [comment] 2020-06-13 19:30
This is actually a duplicate of bvschaik/julius#274

**Closed** 2020-06-14 05:54 UTC
