### ISSUE TITLE
Roadblocks near a granary ignore special orders

### ISSUE THREAD

**Issue by bibelwort** [Keriew/augustus#571] opened 2022-02-18 16:10 UTC
I prefer to use granaries as 'roads'. If I put a roadblock on the first road tile near any entrance to a granary, all walkers on the opposite side cannot path through it despite any special orders.
It seems that walkers don't "see" a road behind the granary, if it starts with a roadblock.

**Comment by scroogie** [comment] 2022-03-08 18:39
I think that's intended behaviour, roadblocks are not treated as road connections, otherwise I could see plenty of problems with adjacent buildings.

**Comment by crudelios** [comment] 2022-03-09 08:46
That's actually a pertinent question, it makes sense that roablocks are not treated as roads when a walker can't cross it, but if the special orders allow for a certain type of walker to go through, then the roadblock should behave as if not existing for that type of walker.

@Keriew What do you think?

**Comment by Keriew** [comment] 2022-03-09 23:02
When to treat roadblocks as roads and when not to is something that I think doesn't have an easy intuitive answer. I think in this case it would be a good idea to change it. I'll get on it.

**Comment by Keriew** [comment] 2022-03-09 23:26
Fixed in d293b87.

**Closed by Keriew** 2022-03-09 23:26 UTC
Labels: bug
