### ISSUE TITLE
Poor Sound Quality using Augustus 3.0.1 on Win 7x64

### ISSUE THREAD

**Issue by Enrada** [Keriew/augustus#436] opened 2021-06-12 21:07 UTC
Hello all,

I have start using Augustus 3.0.1 around a week before.
In general, it works very fine and fulfills very most of my needs and desires on gameplay side.

Concerning the sound,
it shows poor quality (on my system) as all the audio files 
(music, speech, effects) 
are played slower than the original speed (around 90% I guess).

I do not know if the lowered tempo is a random issue or maybe a "feature" which is intended from your side
(from my side, I would prefer to have the original tempo instead of lower tempo)
However, the audio timestretching algorithm shows a very, very poor quality and means a considerable detraction of pleasure on gameplay.
I would be very pleased if you could find a way to improve or remove this bad-working timestretching effect (or to make the usage selectable for user) for one of the next releases?

Many thanks in advance and both thumps up for this fulminant mod!

**Comment by crudelios** [comment] 2021-06-13 07:48
As you may have guessed, the poor audio quality is a bug as the game should play the audio exactly like C3.

I would suggest you start sdl with the pulseaudio windows driver, as mentioned on #194.

**Comment by Enrada** [comment] 2021-06-13 10:50
Alright, 

I have checked the new package found on
http://public.josecadete.net/C3/augustus-new-sdl.zip

The audio quality using this package is far better as with this the official files 3.0.1, but not perfect yet.

There are still artefacts, modulations and crackles in the audio, more randomly and at a lower "modulation frequency".
I am not sure about the remaining timestretch aspect (difficult to compare ~99% against 100%), 
the overall sound characteristic of remaining artefacts is now more like a unstable system which hash too less buffer / latency.

It seems, this changed description of problem is now the same as described by synthc in #194 .

![synthc](https://user-images.githubusercontent.com/85795573/121804198-786ab180-cc45-11eb-88b8-a98e4847db15.PNG)

**Comment by crudelios** [comment] 2021-06-13 15:39
Glad it's better now.

Did you try with the directsound api? It seems to have fixed the issue with synthc.

**Comment by Enrada** [comment] 2021-06-14 02:59
No, I am not familiar with the different api, direct sound, wasapi stuff and actually do not know yet how to deal with that.

**Comment by crudelios** [comment] 2021-06-14 06:12
Open a command line, navigate to your augustus install, then use the following commands:

```
set SDL_AUDIODRIVER=directsound
.\augustus.exe
```

**Comment by Enrada** [comment] 2021-06-14 13:10
Thank you for this instruction.

I just have investigated about that stuff (how to read current status, write a status and delete values of environmental parameters).
First, I checked the initial status of parameter, it seems that SDL_AUDIODRIVER has not been defined at all (no initial value or default value).
Next step, I have executed the write command you gave me.
After this, I also made a read command which confirms that the parameter has the desired value.

Unfortunately, the parameter value "directsound" does not make an improvement, the sound still shows clicks & crackles.

**Comment by Syst3mSh0ck** [comment] 2021-06-21 19:27
This is probably caused by a buffer calculation issue, most likely an underrun.

**Comment by 1bsyl** [comment] 2021-06-25 15:06
hey, 
from https://github.com/Keriew/augustus/issues/194
@synthc said there were no under-run with directsound
is this confirmed ?

**Comment by synthc** [comment] 2021-06-25 18:03
@Enrada Setting environment variables in Windows can be finicky.  Try doing it via system properties instead of command line:
1.  Search for environment variables and click "Edit the system environment variables".
2.  This will bring up System Properties - click "Environment Variables" at the bottom of the window.
3.  Create a new variable in both user and system variables named "SDL_AUDIODRIVER" with a value of "directsound"

**Comment by crudelios** [comment] 2021-09-17 15:21
Now that Augustus is running on the newest version of SDL (2.0.16), this issue should hopefully be fixed.

@1bsyl @Enrada can you please confirm, either by using the latest unstable or by waiting for Augustus v3.1?

**Comment by crudelios** [comment] 2021-12-02 08:49
Since there are no news regarding this, I'm closing the issue.

If the problem persists, please let me know!

**Closed by crudelios** 2021-12-02 08:49 UTC
Labels: bug
