### ISSUE TITLE
Ceres grand temple won't be built

### ISSUE THREAD

**Issue by maistoast** [Keriew/augustus#242] opened 2021-02-15 23:54 UTC
I'm in the Sarmi..something level and I started building the Ceres grand temple but the workers don't appear. If you look closely where the mouse pointer is (see screenshot) there's one worker that appears and immediately disappears. I tried moving the temple, the working camp and the engineering's guild. I tried both the unstable version and the latest stable release.

![C3Bug](https://user-images.githubusercontent.com/24750170/108002475-1039f500-6ff0-11eb-9f37-5a36803cad92.png)
[MattSarmi.zip](https://github.com/Keriew/augustus/files/5984655/MattSarmi.zip)

**Comment by crudelios** [comment] 2021-02-16 00:13
This isn't really a big but the way the game works.

If you notice closely, the marble warehouse has two road networks that are adjacent to it. One in the south side that goes to the native village, and one in the north side that goes to the grand temple.

The problem is, due to the way the game works, each building can only have one road network assigned to it.

In your case, the warehouse is assigned to a different road network than the temple, so the architect can't find its way and immediately disappears.

If you connect both roads the temple construction starts.

**Closed by crudelios** 2021-02-16 00:13 UTC
Labels: bug

**Comment by maistoast** [comment] 2021-02-16 14:11
oh, I didn't see the road in the south.

Thanks

**Comment by crudelios** [comment] 2021-02-16 14:15
No problem.

Road network detection and pathfinding in general is something I want to address in the future.
