### ISSUE TITLE
Granaries Still Need Some Work

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#105] opened 2020-07-09 19:31 UTC
I'm playing Londinium right now.

The problem starts when i have 2 sites of wheat production. Some wheat farms with nearest available granaries (available space and 'accepting' orders), strangelly pick up the farest granary, as you can see on the imagem below.

![Granary 1](https://user-images.githubusercontent.com/64329357/87082192-8688a480-c222-11ea-8360-5be852922423.jpg)

[My City of Londinium.zip](https://github.com/Keriew/augustus/files/4899112/My.City.of.Londinium.zip)

**Comment by Keriew** [comment] 2020-07-11 11:38
Yeah, that's the problem with the default distance function - it depends not only on x and y coordinates of the buildings, but also the distance from the starting point - the outer farms here may be more distant from the granaries to the left, but they also have a similar distance from the road to Rome as the granaries to the left, effectively being "closer". I'll see how hard it'd be to adjust the distance function.

**Comment by cdsmith-umn** [comment] 2020-07-20 19:25
One thing you can do to pre-empt this problem is to keep those farms and their nearby granaries on separate road networks. If there isn't a path between them, then they'll never go there.

**Comment by krs0** [comment] 2020-11-02 20:10
There are multiple issues with granaries : 
2 full granaries will send carts between then endlessly.
Even is a warehouse is set to getting goods it wont get from a granary. You need to put all granaries to stop accepting. to fill that warehouse.

**Comment by cdsmith-umn** [comment] 2020-11-02 20:18
| Even is a warehouse is set to getting goods it wont get from a granary. You need to put all granaries to stop accepting. to fill that warehouse.

That is not a bug. It has always been that way. Warehouses never get from a granary. You either have to have excess production or set the trade advisor to "Stockpile" for that resource in order to fill warehouses.

**Comment by subatron** [comment] 2020-12-14 00:22
> | Even is a warehouse is set to getting goods it wont get from a granary. You need to put all granaries to stop accepting. to fill that warehouse.
> 
> That is not a bug. It has always been that way. Warehouses never get from a granary. You either have to have excess production or set the trade advisor to "Stockpile" for that resource in order to fill warehouses.

Piggybacking off this - I wouldn't want a warehouse getting from a Granary anyway... The Granary's whole job is to store grain/food. I'd even go so far as to say, in a real world situation, that a Granary would store it better than a Warehouse. Plus, there's an option to have Granaries get from each other, even without a road.

**Comment by Areldir** [comment] 2021-01-25 12:33
As this is not directly a bug, and granary prioritisation is an ongoing topic of discussion in the dedicated Discussions tab, I'm closing this issue. Please move all further conversation about granaries to there, until a suitable solution is found and implemented.

**Closed by Areldir** 2021-01-25 12:33 UTC
Labels: bug
